name: Deploy to Amazon Beanstalk

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

  workflow_dispatch:
    inputs:
      setRegion:
        description: 'Set region to deploy:'     
        required: false
        default: 'us-east-1' 
        type: choice
        options:
        - us-east-1
        - us-east-2
      setEnvironment:
        description: 'Set environment to deploy:'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - prd
        - dev
        - stg  
      appName:
        description: 'Application name:'
        required: false
env:
  ENVIRONMENT_NAME: ${{ github.event.inputs.appName }}-${{ github.event.inputs.setEnvironment }}
  VERSION_LABEL: ${{ github.event.inputs.appName }}-${{ github.event.inputs.setEnvironment }}-${{ github.sha }}-${{github.run_number}}
  DEV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    name:  Build
    outputs:
      branchOutput: ${{ steps.ref.outputs.usedBranch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

      if: github.event.inputs.appName == ''
    - id: ref
      run: |
        echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
    
      
    - name: Used vars for dispatch
      if: github.event.inputs.appName != ''
      run: |
        echo "::set-output name=usedEnv::${{ github.event.inputs.setEnvironment }}"    

    - name: Used env master
      if: "${{ env.BRANCH_NAME == 'master' }}"
      run: |
        echo "::set-output name=usedBranch::prd"
    
    - name: Used env staging
      if: "${{ env.BRANCH_NAME == 'staging' }}"
      run: |
        echo "::set-output name=usedBranch::stg"
    
    - name: Used env dev
      if: "${{ env.BRANCH_NAME != 'master' }}"
      run: |
        echo "::set-output name=usedBranch::$DEV"

    - name: Echo branchOutput
      run: |
        echo "${{ steps.ref.outputs.usedBranch }}"
       
  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    outputs:
      appNameOutput: ${{ steps.ref.outputs.usedAppName }}
      regionOutput: ${{ steps.ref.outputs.usedRegion }}

    environment: ${{needs.build.outputs.branchOutput}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Echo branchOutput
      run: |
        echo "${{ needs.build.outputs.branchOutput }}"

    - name: Used vars by push
      if: github.event.inputs.appName == ''
      id: ref2
      run: |
        echo "::set-output name=usedAppName::${{ secrets.SET_NAME }}"
        echo "::set-output name=usedRegion::${{ secrets.SET_REGION }}"

    - name: Used vars by workflow dispatch
      if: github.event.inputs.appName != ''
      run: |
        echo "::set-output name=usedAppName::${{ github.event.inputs.appName }}"
        echo "::set-output name=usedRegion::${{ github.event.inputs.setRegion }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ steps.ref2.outputs.usedRegion }}

    - name: Build
      run: |
        cd ./app
        zip -r app.zip .

    - name: Deploy Amazon Beanstalk
      run: |
        aws s3 cp ./app/app.zip s3://$ENVIRONMENT_NAME-bucket/${{needs.build.outputs.branchOutput}}/$VERSION_LABEL
        aws --region ${{needs.build.outputs.regionOutput}} elasticbeanstalk create-application-version --application-name ${{needs.build.outputs.appNameOutput}} --version-label $VERSION_LABEL --source-bundle S3Bucket=$ENVIRONMENT_NAME-bucket,S3Key=${{needs.build.outputs.branchOutput}}/$VERSION_LABEL
        aws --region ${{needs.build.outputs.regionOutput}} elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $VERSION_LABEL

    - name: Check Environment
      run: |
        aws elasticbeanstalk describe-environments --region ${{ env.outputRegion }} --application-name ${{needs.build.outputs.appNameOutput}} --environment-names $ENVIRONMENT_NAME
