name: Deploy to Amazon Beanstalk

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      setRegion:
        description: 'Set region to deploy:'     
        required: true
        default: 'us-east-1' 
        type: choice
        options:
        - us-east-1
        - us-east-2
      setEnvironment:
        description: 'Set environment to deploy:'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - prd
        - dev
        - stg  
      appName:
        description: 'Application name:'
        required: true
env:
  AWS_REGION: ${{ github.event.inputs.setRegion }}                                                      # set this to your preferred AWS region, e.g. us-west-1
  ENV: ${{ github.event.inputs.setEnvironment }} 
  APP_NAME: ${{ github.event.inputs.appName }}
  ENVIRONMENT_NAME: ${{ github.event.inputs.appName }}-${{ github.event.inputs.setEnvironment }}
  VERSION_LABEL: ${{ github.event.inputs.appName }}-${{ github.event.inputs.setEnvironment }}-${{ github.sha }}-${{github.run_number}}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.setEnvironment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build
      run: |
        cd ./app
        zip -r app.zip .

    - name: Deploy Amazon Beanstalk
      run: |
        aws s3 cp ./app/app.zip s3://$ENVIRONMENT_NAME-bucket/$ENV/$VERSION_LABEL
        aws --region $AWS_REGION elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket=$ENVIRONMENT_NAME-bucket,S3Key=$ENV/$VERSION_LABEL
        aws --region $AWS_REGION elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $VERSION_LABEL

    - name: Check Environment
      run: |
        aws elasticbeanstalk describe-environments --region $AWS_REGION --application-name $APP_NAME --environment-names $ENVIRONMENT_NAME